#!/bin/bash


## Intro: Bash script invoked by [bm]
## Title: properd {{{1
## Author: Mario Fantini ing.mariofantini@gmail.com https://github.com/MartDiVenus/ {{{1

## Copyright (C) 2021.10.15 {{{1 
# Creative Commons by-nc-sa-eu

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You have received a copy of the GNU General Public License
# along with this program in README/COPYING. 
# Aka see <https://www.gnu.org/licenses/>.

## Help: Vale-netrw_bm
ù

sudo rm -fr /tmp/splitValeNetrw-SMarked

mkdir /tmp/splitValeNetrw-SMarked

split -l1 /tmp/valeNetrw-SMarked /tmp/splitValeNetrw-SMarked/

for a in $(ls /tmp/splitValeNetrw-SMarked)
do
	leggoA=$(cat /tmp/splitValeNetrw-SMarked/$a)
	sudo -S chown $USER:$USER $leggoA
        sudo -S chmod uga+xrw $leggoA
done

sudo rm -r /tmp/splitValeNetrw-SMarked /tmp/valeNetrw-SMarked





exit

 


