#!/bin/bash

## Intro: Bash script invoked by [bd]
## Title: properd {{{1
## Author: Mario Fantini marfant7@gmail.com https://github.com/MartDiVenus/ {{{1

## Copyright (C) 2021.10.15 {{{1 
# Creative Commons by-nc-sa-eu

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You have received a copy of the GNU General Public License
# along with this program in README/COPYING. 
# Aka see <https://www.gnu.org/licenses/>.

## Help: Vale-netrw_bd


sudo rm -fr /tmp/splitValeNetrw-DMarked

mkdir /tmp/splitValeNetrw-DMarked

split -l1 /tmp/valeNetrw-DMarked /tmp/splitValeNetrw-DMarked/

for a in $(ls /tmp/splitValeNetrw-DMarked)
do
	leggoA=$(cat /tmp/splitValeNetrw-DMarked/$a)
	sudo -S chown -R $USER:$USER $leggoA
        sudo -S chmod -R uga+xrw $leggoA
done

sudo rm -r /tmp/splitValeNetrw-DMarked /tmp/valeNetrw-DMarked





exit

 


